"""Transaction added

Revision ID: 6281048414e4
Revises: 1f3da4199a81
Create Date: 2024-08-28 15:19:12.986575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6281048414e4'
down_revision: Union[str, None] = '1f3da4199a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('tx_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.alter_column('user', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('transaction')
    # ### end Alembic commands ###
