"""Delete hash column

Revision ID: 6f2346ddc319
Revises: 6281048414e4
Create Date: 2024-08-28 21:27:37.684649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2346ddc319'
down_revision: Union[str, None] = '6281048414e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_tx_hash_key', 'transaction', type_='unique')
    op.drop_column('transaction', 'tx_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('tx_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('transaction_tx_hash_key', 'transaction', ['tx_hash'])
    # ### end Alembic commands ###
